name: openvb
description: A open source Visual Basic interpreter written in Dart.
version: 0.0.1
repository: https://github.com/pptos-org/openvb

environment:
  sdk: ^3.4.4

dependencies:
  web: ^1.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
