name: openvb
description: A open source Visual Basic interpreter written in Dart.
version: 0.0.1
repository: https://github.com/pptos-org/openvb

environment:
  sdk: ^3.4.4

dependencies:
  web: ^1.0.0
  file_system_access_api: ^2.0.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
  build_runner: ^2.4.12
  build_test: ^2.2.2
  build_web_compilers: ^4.0.11
  source_map_stack_trace: ^2.1.2
