name: Build openvb for Linux

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    steps:
      - uses: actions/checkout@v4
      - uses: dart-lang/setup-dart@9a04e6d73cca37bd455e0608d7e5092f881fd603

      - name: Build openvb for Linux
        run: |
          build.sh build_native
        shell: bash

      - name: Upload Binary
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./bin/openvb-*"
          allowUpdates: true
          tag: "aplha"
