name: Build openvb for Linux arm64

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Install Dart SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https wget
          wget -qO- https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'wget -qO- https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list > /etc/apt/sources.list.d/dart_stable.list'
          sudo apt-get update
          sudo apt-get install dart
        env:
          DEBIAN_FRONTEND: noninteractive

      - name: Build openvb for Linux
        run: |
          ./build.sh build_native
        shell: bash

      - name: Upload Binary
        uses: ncipollo/release-action@v1
        with:
          artifacts: "./bin/openvb-*"
          allowUpdates: true
          tag: "alpha"
